In [148]:
# Cài 1 số gói hỗ trợ
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [149]:
# Đọc dữ liệu
data = pd.read_csv('aus.csv')

In [137]:
data.head()

Att1   Att2   Att3  Att4  Att5  Att6   Att7  Att8  Att9  Att10  Att11  \
0     1  22.08  11.46     2     4     4  1.585     0     0      0      1   
1     0  22.67   7.00     2     8     4  0.165     0     0      0      0   
2     0  29.58   1.75     1     4     4  1.250     0     0      0      1   
3     0  21.67  11.50     1     5     3  0.000     1     1     11      1   
4     1  20.17   8.17     2     6     4  1.960     1     1     14      0   

   Att12  Att13  Att14  Target  
0      2    100   1213       0  
1      2    160      1       0  
2      2    280      1       0  
3      2      0      1       1  
4      2     60    159       1

In [150]:
X = data.iloc[:, :14]
y = data.Target

In [139]:
X

Att1   Att2    Att3  Att4  Att5  Att6   Att7  Att8  Att9  Att10  Att11  \
0       1  22.08  11.460     2     4     4  1.585     0     0      0      1   
1       0  22.67   7.000     2     8     4  0.165     0     0      0      0   
2       0  29.58   1.750     1     4     4  1.250     0     0      0      1   
3       0  21.67  11.500     1     5     3  0.000     1     1     11      1   
4       1  20.17   8.170     2     6     4  1.960     1     1     14      0   
..    ...    ...     ...   ...   ...   ...    ...   ...   ...    ...    ...   
685     1  31.57  10.500     2    14     4  6.500     1     0      0      0   
686     1  20.67   0.415     2     8     4  0.125     0     0      0      0   
687     0  18.83   9.540     2     6     4  0.085     1     0      0      0   
688     0  27.42  14.500     2    14     8  3.085     1     1      1      0   
689     1  41.00   0.040     2    10     4  0.040     0     1      1      0   

     Att12  Att13  Att14  
0        2    100   1213  
1        2    160      1  
2        2    280      1  
3        2      0      1  
4        2     60    159  
..     ...    ...    ...  
685      2      0      1  
686      2      0     45  
687      2    100      1  
688      2    120     12  
689      1    560      1  

[690 rows x 14 columns]

In [151]:
# Chia dữ liệu 2 tập train-test
# Từ tập train -> ước lượng w
# Từ tập test -> kiểm định w (hàm f) tìm được có tốt ko
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [152]:
# ước lượng w nhờ X_train, y_train
X_train = X_train.values
X_train = X_train.transpose()
y_train = y_train.values
X_test = X_test.transpose()
X_train = np.concatenate((np.ones((1, X_train.shape[1])), X_train), axis = 0)
X_test = np.concatenate((np.ones((1, X_test.shape[1])), X_test), axis = 0)

In [153]:
X_train

array([[1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [2.617e+01, 3.450e+01, 3.908e+01, ..., 1.917e+01, 1.608e+01,
        2.767e+01],
       ...,
       [2.000e+00, 2.000e+00, 2.000e+00, ..., 2.000e+00, 2.000e+00,
        2.000e+00],
       [1.000e+02, 1.950e+02, 1.080e+02, ..., 8.000e+01, 3.520e+02,
        4.870e+02],
       [1.000e+00, 1.000e+00, 1.098e+03, ..., 4.850e+02, 6.910e+02,
        5.010e+02]])

In [ ]:
X_test

In [142]:
def sigmoid(s):
    return 1/(1 + np.exp(-s))

def logistic_sigmoid_regression(X, y, w_init, eta, tol = 1e-4, max_count = 500000):
    w = [w_init]    
    it = 0
    N = X.shape[1]
    d = X.shape[0]
    count = 0
    check_w_after = 20
    while count < max_count:
        # mix data 
        mix_id = np.random.permutation(N)
        for i in mix_id:
            xi = X[:, i].reshape(d, 1)
            yi = y[i]
            zi = sigmoid(np.dot(w[-1].T, xi))
            w_new = w[-1] + eta*(yi - zi)*xi
            count += 1
            # stopping criteria
            if count%check_w_after == 0:                
                if np.linalg.norm(w_new - w[-check_w_after]) < tol:
                    return w
            w.append(w_new)
    return w

In [143]:
eta = .001 
d = X_train.shape[0]
w_init = np.random.randn(d, 1)

w = logistic_sigmoid_regression(X_train, y_train, w_init, eta)

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [144]:
w[-1]

array([[-3.37795919],
       [-0.85719533],
       [-4.67189625],
       [ 1.65587461],
       [-0.9054791 ],
       [ 9.08244217],
       [-1.44378351],
       [10.64357122],
       [ 3.85233646],
       [ 0.36250748],
       [10.76091649],
       [ 0.35385747],
       [-3.3142836 ],
       [ 0.01753452],
       [ 0.15489097]])

In [145]:
# <0.5 -> 0;  >= 0.5 -> 1
def predict(f):
    f = f.reshape(-1)
    f = pd.DataFrame(f, columns = ['sigmoid'])
    #print(f)
    f['Target_pred'] = 0
    f.loc[f[f['sigmoid'] >= 0.5].index, 'Target_pred'] = 1
    return f

In [146]:
# Dự đoán khách hàng nằm trong tập X_test
# Tìm độ chính mô hình logistic ??? w có tố k?
f = sigmoid(np.dot(w[-1].T, X_test))
target_pred = predict(f)

In [134]:
target_pred

sigmoid  Target_pred
0     1.000000e+00            1
1     9.999577e-01            1
2     1.223194e-67            0
3     1.000000e+00            1
4     9.932357e-01            1
..             ...          ...
168   9.999861e-01            1
169   6.763569e-08            0
170   1.159421e-21            0
171  7.459570e-141            0
172   1.000000e+00            1

[173 rows x 2 columns]

In [81]:
# Đánh giá mô hình bằng độ chính xác
from sklearn.metrics import accuracy_score
accuracy_score(y_test.values, target_pred.Target_pred.values)

0.8034682080924855

In [82]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test.values, target_pred.Target_pred.values)

array([[94, 13],
       [21, 45]], dtype=int64)